version: '3'

services:
  flask:
    build: ./server
    ports:
      - 127.0.0.1:5000:5000
    restart: always
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      VIRTUAL_HOST: ${HOST}
      VIRTUAL_PORT: 5000
#      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: ${HOST}
      LETSENCRYPT_EMAIL: ${EMAIL}
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./setup.conf:/usr/src/setup.conf

# SEE: https://github.com/buchdag/letsencrypt-nginx-proxy-companion-compose/blob/master/2-containers/compose-v3/labels/docker-compose.yaml
# For examples on how to set up the letsencrypt service
  nginx_proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx_proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - 80:80
      - 443:443
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx_proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs: